name: Deploy Client To Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install PNPM
        run: npm install -g pnpm@10

      - name: Install Dependencies
        working-directory: ./client
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: ./client
        run: pnpm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: "./client/dist"
          production-branch: main
          github-token: ${{ secrets.ACCESS_TOKEN_GITHUB }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 2
